import Categories from "@/components/Categories";

export const metadata = {
  title: "Products",
  description: "Generated by create next app",
};

export default function ProductsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="py-20 border-dashed">
      <div className="container">
        <div className="grid grid-cols-5 gap-5">
          <div className="col-span-1 sticky top-10 self-start">
            <Categories />
          </div>
          <div className="text-md font-semibold text-dark col-span-4 ">
            {children}
          </div>
        </div>
      </div>
    </section>
  );
}
