"use client";
import type { Metadata } from "next";
import "./globals.css";
import CartContext from "@/store/slice";
import { useEffect, useState } from "react";
import { getLocalStorageItem, setLocalStorageItem } from "../../helper";

// export const metadata: Metadata = {
//   title: "Geoshop",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [cart, setCart] = useState([]);

  const savedCart = getLocalStorageItem("cart");

  useEffect(() => {
    if (savedCart) setCart(JSON.parse(savedCart));
    else {
      // If no cart exists, create one
      setLocalStorageItem("cart", JSON.stringify(cart));
    }
  }, []);

  return (
    <CartContext.Provider value={{ cart, setCart }}>
      <html lang="en">
        <body>{children}</body>
      </html>
    </CartContext.Provider>
  );
}
